version: '3.8'
services:
  spillhuset-bot:
    image: ghcr.io/notbjoggisatall/spillhuset-bot:1.10
    restart: always
    container_name: spillhuset-bot
    environment:
      - SPRING_PROFILES_ACTIVE=docker,prod
    ports:
      - '8400:8400'
    volumes:
      - 'utils:/utils'
    networks:
      - 'internal'
networks:
  internal:
    external: true
volumes:
  utils:
    external: true
