apiVersion: apps/v1
kind: Deployment
metadata:
  name: spillhuset-bot-deployment
  namespace: default
  labels:
    app: spillhuset-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spillhuset-bot
  template:
    metadata:
      labels:
        app: spillhuset-bot
    spec:
      containers:
        - name: spillhuset-bot
          image: ghcr.io/notbjoggisatall/spillhuset-bot:1.22
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: credentials
---
apiVersion: v1
kind: Service
metadata:
  name: spillhuset-bot-service
spec:
  selector:
    app: spillhuset-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spillhuset-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: spillhuset-api.bjoggis.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: spillhuset-bot-service
                port:
                  number: 80